name: On pull request creation

on:
  pull_request:
    branches: [ main ]

jobs:
  Sample_Run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Initialize Browser Library
        run: |
          rfbrowser init

      - name: Run Robot Framework tests
        run: |
          robot -d SwagLabs_Report -v PROJECT:SWAGLABS -v HEADLESS:False -i Swaglabs .

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: SwagLabs_Report_results
          path: SwagLabs_Report/
    
